FROM node:16-alpine

WORKDIR '/home/node/app'

#COPY package.json .
COPY --chown=node:node ./package.json ./

RUN npm config set fetch-retry-mintimeout 2000000
RUN npm config set fetch-retry-maxtimeout 12000000
#RUN npm config set registry http://registry.npmjs.org/ 
RUN npm install

#COPY . .
COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]